version: '3'
services:
  postgres: 
    image: postgres:13
    container_name: postgres_db
    environment:
      postgres_user: postgres
      postgres_password: postgres
      postgres_db: postgres
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    
volumes:
  postgres_data: